--
-- PostgreSQL database dump
--

-- Dumped from database version 13.1
-- Dumped by pg_dump version 13.1

-- Started on 2021-01-16 14:48:08

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE "restAPI";
--
-- TOC entry 3032 (class 1262 OID 24576)
-- Name: restAPI; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "restAPI" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'Portuguese_Portugal.1252';


ALTER DATABASE "restAPI" OWNER TO postgres;

\connect "restAPI"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3033 (class 0 OID 0)
-- Dependencies: 3032
-- Name: DATABASE "restAPI"; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON DATABASE "restAPI" IS 'Database for Rest API SDP project';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 202 (class 1259 OID 24592)
-- Name: delivery; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.delivery (
    id integer NOT NULL,
    address character varying(255)
);


ALTER TABLE public.delivery OWNER TO postgres;

--
-- TOC entry 206 (class 1259 OID 24626)
-- Name: delivery_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.delivery ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.delivery_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 255
    CACHE 1
);


--
-- TOC entry 208 (class 1259 OID 24647)
-- Name: deliveryitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.deliveryitem (
    delivery_id integer,
    id integer NOT NULL,
    item_id integer,
    qty integer
);


ALTER TABLE public.deliveryitem OWNER TO postgres;

--
-- TOC entry 207 (class 1259 OID 24645)
-- Name: deliveryitem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.deliveryitem ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.deliveryitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 5000
    CACHE 1
);


--
-- TOC entry 201 (class 1259 OID 24582)
-- Name: deposit; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.deposit (
    id integer NOT NULL,
    qty integer NOT NULL,
    item_id integer NOT NULL
);


ALTER TABLE public.deposit OWNER TO postgres;

--
-- TOC entry 204 (class 1259 OID 24622)
-- Name: deposit_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.deposit ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.deposit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 255
    CACHE 1
);


--
-- TOC entry 200 (class 1259 OID 24577)
-- Name: item; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.item (
    id integer NOT NULL,
    name character varying(60),
    description character varying(255)
);


ALTER TABLE public.item OWNER TO postgres;

--
-- TOC entry 205 (class 1259 OID 24624)
-- Name: item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.item ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 255
    CACHE 1
);


--
-- TOC entry 203 (class 1259 OID 24612)
-- Name: stock; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.stock (
    item_id integer NOT NULL,
    stock integer
);


ALTER TABLE public.stock OWNER TO postgres;

--
-- TOC entry 3020 (class 0 OID 24592)
-- Dependencies: 202
-- Data for Name: delivery; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.delivery (id, address) FROM stdin;
\.


--
-- TOC entry 3026 (class 0 OID 24647)
-- Dependencies: 208
-- Data for Name: deliveryitem; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.deliveryitem (delivery_id, id, item_id, qty) FROM stdin;
\.


--
-- TOC entry 3019 (class 0 OID 24582)
-- Dependencies: 201
-- Data for Name: deposit; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.deposit (id, qty, item_id) FROM stdin;
\.


--
-- TOC entry 3018 (class 0 OID 24577)
-- Dependencies: 200
-- Data for Name: item; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.item (id, name, description) FROM stdin;
\.


--
-- TOC entry 3021 (class 0 OID 24612)
-- Dependencies: 203
-- Data for Name: stock; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.stock (item_id, stock) FROM stdin;
\.


--
-- TOC entry 3034 (class 0 OID 0)
-- Dependencies: 206
-- Name: delivery_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.delivery_id_seq', 29, true);


--
-- TOC entry 3035 (class 0 OID 0)
-- Dependencies: 207
-- Name: deliveryitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.deliveryitem_id_seq', 22, true);


--
-- TOC entry 3036 (class 0 OID 0)
-- Dependencies: 204
-- Name: deposit_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.deposit_id_seq', 15, true);


--
-- TOC entry 3037 (class 0 OID 0)
-- Dependencies: 205
-- Name: item_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.item_id_seq', 31, true);


--
-- TOC entry 2879 (class 2606 OID 24596)
-- Name: delivery delivery_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delivery
    ADD CONSTRAINT delivery_pkey PRIMARY KEY (id);


--
-- TOC entry 2883 (class 2606 OID 24651)
-- Name: deliveryitem deliveryitem_id; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.deliveryitem
    ADD CONSTRAINT deliveryitem_id PRIMARY KEY (id);


--
-- TOC entry 2873 (class 2606 OID 24581)
-- Name: item deposit_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.item
    ADD CONSTRAINT deposit_pkey PRIMARY KEY (id);


--
-- TOC entry 2877 (class 2606 OID 24586)
-- Name: deposit deposit_pkey1; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.deposit
    ADD CONSTRAINT deposit_pkey1 PRIMARY KEY (id);


--
-- TOC entry 2875 (class 2606 OID 24663)
-- Name: item name_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.item
    ADD CONSTRAINT name_unique UNIQUE (name);


--
-- TOC entry 2881 (class 2606 OID 24616)
-- Name: stock stock_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stock
    ADD CONSTRAINT stock_pkey PRIMARY KEY (item_id);


--
-- TOC entry 2886 (class 2606 OID 24652)
-- Name: deliveryitem delivery_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.deliveryitem
    ADD CONSTRAINT delivery_id FOREIGN KEY (delivery_id) REFERENCES public.delivery(id);


--
-- TOC entry 2884 (class 2606 OID 24587)
-- Name: deposit item_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.deposit
    ADD CONSTRAINT item_id FOREIGN KEY (item_id) REFERENCES public.item(id) NOT VALID;


--
-- TOC entry 2885 (class 2606 OID 24617)
-- Name: stock item_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stock
    ADD CONSTRAINT item_id FOREIGN KEY (item_id) REFERENCES public.item(id);


--
-- TOC entry 2887 (class 2606 OID 24657)
-- Name: deliveryitem item_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.deliveryitem
    ADD CONSTRAINT item_id FOREIGN KEY (item_id) REFERENCES public.item(id);


-- Completed on 2021-01-16 14:48:08

--
-- PostgreSQL database dump complete
--

